name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts
          ssh -i <(echo "$EC2_SSH_KEY") $EC2_USER@$EC2_HOST << EOF
            cd /home/ubuntu/aws_test
            git pull origin master  # Pull the latest code
            docker stop my_app
            docker build -t my_app .
            docker run -e RAILS_MASTER_KEY=$RAILS_MASTER_KEY -p 3000:3000 -t my_app
            # Add commands to restart your application
          EOF
